# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u6n5oR7wPHhWadzRasoTm-v-2LtXj60U
"""

num1= eval(input('Digite um valor: '))
num2= eval(input('Digite outro valor: '))
soma = num1+num2
print('A soma entre {} e {} é igual a {}'.format(num1, num2, soma))